Algoritmo "ImparPar"
// Disciplina   : pa
// Professor   : Cintia Pinho
// Descrição   :  Identificar se o numero digitado é impar ou par.
// Autor(a)    : Danilo Correia
// Data atual  : 26/07/2022
Var
numero:inteiro


Inicio
//entrada
escreval(" Digite um numero para saber se ele é impar ou par: ")
leia(numero)

//processamento

se ( numero mod 2=0 ) entao
escreval("esse numero é par")

senao
escreval("o numero é impar")
fimse


Fimalgoritmo