Algoritmo "lacosderepetiçao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Dan C
// Data atual  : 23/08/2022
Var
cont, acu:inteiro


Inicio
escreval("----------------- LACO PARA ------------")

para cont de 1 ate 20 faca


escreval(cont)

fimpara

Fimalgoritmo