Algoritmo "exc3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   :
// Autor(a)    :
// Data atual  : 25/10/2022
Var
andar: vetor[1..4,1..6]
coluna,linha,pessoa,cont:inteiro


Inicio
para coluna de 1 ate 6 faca
   para linha de 1 ate 4 faca
    cont <- cont+1
   escreval("Quantas pessoas moram no primeiro andar?")
   leia(pessoa)
   
   

fimpara



Fimalgoritmo