algoritmo "conversao"
// Função : fazer a conversao de reais para dollar
// Autor : Danilo Correia
// Data : 03/05/2022
// Seção de Declarações 
var
cotdolar,valor,valorC: real


inicio
//entrada
escreval("Digite a cotação do dollar atual: ")
leia(cotdolar)

escreval("Digite o valor que quer converter para dollar: ")
leia(valor)

//processamento

valorC <- valor/cotdolar


//saida

escreval("O valor em dolar é:  " ,valorC)






fimalgoritmo
