algoritmo "pecacalculo"
// Função : Ache o valor da comissao sobre a pecas vendidas
// Autor :
// Data : 03/05/2022
// Seção de Declarações 
var
valor,qtde,total:real


inicio
//inicio
escreval("Digite o preço unitario da peça: ")
leia(valor)

escreval("Digite a quantidade vendida:  ")
leia(qtde)

//processamento

total <-(valor*qtde)

//saida

escreval("A sua comissão vai ser:" ,total)



fimalgoritmo
