Algoritmo "exc13"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Soma todos os números primos de de 1 a 100
// Autor(a)    : Danilo Correia
// Data atual  : 20/09/2022
Var
soma:inteiro

Inicio

soma <- 3+ 5+ 7+ 11+ 13+ 17+ 19+ 23+ 29+ 31+ 37+ 41+ 43+ 47+ 53+ 59+ 61+ 67+ 71+ 73+ 79+ 83+ 89+ 97

escreval(" O total da soma dos números primos de 1 a 100 é igual a:", soma)




Fimalgoritmo