Algoritmo "num_inteiros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : leia 10 números inteiros e apresente a soma de todos os números
// Autor(a)    : Danilo Correia
// Data atual  : 06/09/2022
Var
cont,acu:inteiro




Inicio
para cont de 1 ate 10  faca
     acu <- acu+ cont
     escreval(acu)
fimpara

escreval ("A soma dos 10 primeiros numeros inteiros é:", acu)



Fimalgoritmo