Algoritmo "num_7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : leia 10 números inteiros e apresente a soma de todos os números
// Autor(a)    : Danilo Correia
// Data atual  : 06/09/2022
Var
cont,acu,numero:inteiro


Inicio
repita

   para cont de 1 ate 2  faca
   escreval("Digite um numero para fazer a soma:")
   leia(numero)
        acu <- acu+cont
        escreval(acu)
   fimpara


ate(numero=0)

Fimalgoritmo