Algoritmo "numeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   :  Mostrar na tela os numeros de um ponto inical até o final.
// Autor(a)    : Danilo Correia
// Data atual  : 06/09/2022
Var
cont,a1,a2:inteiro

Inicio
escreval("Por onde deseja começar?")
leia(a1)

escreval("Por onde deseja terminar?")
leia(a2)

para cont de a1 ate a2 faca

escreval(cont)

fimpara




Fimalgoritmo