Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : escreva a tabuada de um número informado pelo usuário
// Autor(a)    : Danilo Correia
// Data atual  : 06/09/2022
Var
n,tb,acu,cont:inteiro



Inicio
escreval("Digite um numero que queira saber a tabuada")
leia(tb)

para cont de 1 ate 10  faca
     acu <- acu+tb
     escreval(acu)
fimpara





Fimalgoritmo